### ISSUE TITLE
idea/question: support newer PKCS12 based formats?

### ISSUE THREAD

**Issue by nitram509** [pavlo-v-chernykh/keystore-go#47]
Hi,

while I incorporated your great lib into my app, I figured out that Oracle changed the default JKS format to PKCS12 *1.
I stumbled upon this issue because I got the error "magic bytes are wrong".
While I quickly verified my installed JDKs ... it seems that Temurin picked up this change later, with v20.
Without further analysis, I do assume the various JDKs/JREs do use one or the other format.

Since I assume also other users of your great lib will sooner or later face this issue,
I wonder if you would be interested in extending your lib to support this PKCS12 format?
Or - in case I would provide a PR - would you consider merging it?

*1) See [Consolidated JDK 9 Release Notes - Change in the default keystore type to PKCS12](https://www.oracle.com/java/technologies/javase/9-all-relnotes.html#JDK-8044445)

Regards
Martin

**Comment by pavlo-v-chernykh** [comment]
Hi Martin (@nitram509)

Big thanks for checking out my library and for your suggestion on PKCS12. As you've noticed, the library was originally intended to work with the legacy JKS format. Implementing support for PKCS12 from scratch is quite a complex task. There is a library for PKCS12 https://github.com/SSLMate/go-pkcs12 implemented in Golang. When I last looked at it https://github.com/pavlo-v-chernykh/keystore-go/issues/37, it lacked the necessary functionality to support all the scenarios (password-protected/passwordless, encode/decode) and be compatible with JDK's keytool. But the library is in development, so things could change since I last looked into it, and can be used as a foundation of PKCS12 support here. So if you are considering contributing, please, make sure your implementation supports all the scenarios (password-protected/passwordless, encode/decode) and compatible with keytool from JDK.

Best of luck to you, 
Pavlo
